server:
  port: 0 # 随机端口

spring:
  config:
    import:
      - optional:file:./program-config.yml  # 试试当前目录
      - optional:file:../program-config.yml # 试试上级目录
  application:
    name: statistics-backend # 这个名字要和网关配置里的 lb:// 后面一致
  cloud:
    nacos:
      discovery:
        server-addr: ${nacos.host:localhost}:${nacos.port:8848}

  # RabbitMQ 配置
  rabbitmq:
    host: ${rabbitmq.host:localhost}
    port: ${rabbitmq.port:5672}
    username: ${rabbitmq.username:guest}
    password: ${rabbitmq.password:guest}
    virtual-host: ${rabbitmq.virtual-host:/}
    listener:
      simple:
        acknowledge-mode: auto
        prefetch: 10


# 活动服务配置
activity:
  service:
    base-url: http://petcare-backend  # 你的活动服务地址

# 日志配置
logging:
  level:
    com.example.stats: DEBUG