spring.application.name=llm-backend
# GraphQL??
spring.graphql.graphiql.enabled=true
spring.graphql.path=/graphql
spring.graphql.schema.locations=classpath:graphql/

# ????
server.port=8088

# ????
logging.level.com.example.demo.resolver=DEBUG